<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Edison
 * Date: 12-5-27
 * Time: 下午4:47
 * To change this template use File | Settings | File Templates.
 */

function intern_core_node_insert($node) {
  _intern_core_expire_node($node);
}

function intern_core_node_update($node) {
  _intern_core_expire_node($node);
}

function intern_core_node_delete($node) {
  _intern_core_expire_node($node);
}

function intern_core_comment_insert($comment) {
  if (!empty($comment->nid)) {
    $node = node_load($comment->nid);
    if ($node) {
      _intern_core_expire_node($node);
    }
  }
}

/**
 * Implements hook_comment_update().
 *
 * Acts on comments updates.
 */
function intern_core_comment_update($comment) {
  if (!empty($comment->nid)) {
    $node = node_load($comment->nid);
    if ($node) {
      _intern_core_expire_node($node);
    }
  }
}

/**
 * Implements hook_comment_update().
 *
 * Acts on comments updates.
 */
function intern_core_comment_delete($comment) {
  if (!empty($comment->nid)) {
    $node = node_load($comment->nid);
    if ($node) {
      _intern_core_expire_node($node);
    }
  }
}

function _intern_core_expire_node($node) {

  global $user, $base_path,$base_root;
  if ($node->type == 'review') {
    $cache_key = $key = _authcache_key($user) . $_SERVER['HTTP_REFERER'];
  }
  else {
    if ($node->type == 'company' || $node->type == 'article') {
      $cache_key = $key = _authcache_key($user) .$base_root. $base_path .$node->type . '/' . $node->nid;
    }
  }

  if (isset($cache_key)) {
    //  watchdog('expire node',$cache_key);
    cache_clear_all($cache_key, 'cache_page');
  }
}

function i_title($nid){
  $title = db_select('node', 'm')
    ->fields('m', array('title'))
    ->condition('nid', $nid)
    ->range(0, 1)
    ->execute()
    ->fetchField();
  return $title;
}

function i_field($nid,$field_name){
  $field_value = db_select('field_data_'.$field_name, 'm')
    ->fields('m', array($field_name.'_value'))
    ->condition('entity_id', $nid)
    ->range(0, 1)
    ->execute()
    ->fetchField();
  return $field_value;
}

function intern_core_get_vote_info( $field_name,$gid){
  $sql = "select count(*)  as count,avg(".$field_name."_rating) as rate from {field_data_".$field_name."}
  where entity_id in (select etid from {og_membership} where gid=:gid)";
  $record = db_query($sql, array(':gid' => $gid));
  foreach ($record as $rec) {
    $result = array("count"=>$rec->count,'rate'=> $rec->rate);
  }
  $rate = $result['rate'];

  $output='<div class="fivestar-widget clearfix fivestar-widget-5">
         <div class="star star-1 odd '.($rate>20?'on':'').'"><a></a></div>
         <div class="star star-2 even '.($rate>40?'on':'').'"><a></a></div>
         <div class="star star-3 odd '.($rate>60?'on':'').'"><a></a></div>
         <div class="star star-4 even '.($rate>80?'on':'').'"><a></a></div>
         <div class="star star-5 odd '.($rate>95?'on':'').'"><a></a></div>
         <div><span>['.$result['count'].']</span></div>
    </div>
  ';
  return $output;
}

function intern_core_get_vote_score( $field_name,$gid,$label){
  $sql = "select count(*)  as count,round(avg(".$field_name."_rating)/10,1) as rate from {field_data_".$field_name."}
  where entity_id in (select etid from {og_membership} where gid=:gid)";
  $record = db_query($sql, array(':gid' => $gid));
  foreach ($record as $rec) {
    $result = array("count"=>$rec->count,'rate'=> $rec->rate);
  }
  $rate = $result['rate'];
  $count = $result['count'];
  $output = '';
  if($count>0){
      $output = '<span class="vote-score">'.$label.'：<span class="rate-value">'.$rate."</span></span>";
  }
  return $output;
}

function intern_core_render_vote($label,$vote){

  $output ='';
  if(strpos($vote,'0/5')>0){

  }else if(strpos($vote,'1/5')){
    $output = '<span class="rate-item">'.$label.'1<span class="c-11">(很差)</span></span>';
  } else if(strpos($vote,'2/5')){
    $output = '<span class="rate-item">'.$label.'2<span class="c-11">(一般)</span></span>';
  }   else if(strpos($vote,'3/5')){
    $output = '<span class="rate-item">'.$label.'3<span class="c-11">(好)</span></span>';
  }else if(strpos($vote,'4/5')){
    $output = '<span class="rate-item">'.$label.'4<span class="c-11">(很好)</span></span>';
  }else if(strpos($vote,'5/5')){
    $output = '<span class="rate-item">'.$label.'5<span class="c-11 small">(非常好)</span></span>';
  }
  return $output;
}


