<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Edison
 * Date: 12-5-27
 * Time: 下午4:47
 * To change this template use File | Settings | File Templates.
 */
//草稿
define("JOB_SUB_STATUS_DRAFT", 0);
//已暂停
define("JOB_SUB_STATUS_STOPPED", 1);
//已过期
define("JOB_SUB_STATUS_EXPIRED", 2);
//待审核
define("JOB_SUB_STATUS_REQUIRE_APPROVAL", 3);
//发布中
define("JOB_SUB_STATUS_PUBLISHED", 4);
//即将到期
define("JOB_SUB_STATUS_NEARLY_EXPIRED", 10);

define('JOB_ACTION_REFRESH', '0');
define('JOB_ACTION_STOP', '1');
define('JOB_ACTION_REPUBLISH', '2');

define("DATE_ONE_MONTH", 3600 * 24 * 30);
/**
 * Implements hook_menu().
 */
function intern_job_menu() {
  $items['job/actions/%/%'] = array(
    'title' => 'Job Actions',
    'page callback' => 'intern_job_action_page',
    'page arguments' => array(2, 3),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function intern_job_action_page($action_type, $nid) {
  $node = node_load($nid);
  if ($action_type == JOB_ACTION_REFRESH) {
    _intern_job_refresh($node);
    node_save($node);
    drupal_set_message(t("刷新操作成功。"));
  }
  else {
    if ($action_type == JOB_ACTION_STOP) {
      _intern_job_stop($node);
      node_save($node);
      drupal_set_message(t("职位已暂停。"));
    }
    else {
      if ($action_type == JOB_ACTION_REPUBLISH) {
        _intern_job_republish($node);
        node_save($node);
        drupal_set_message(t("职位再发布成功。"));
      }
    }
  }


  drupal_goto();
}

/**
 * @param $node
 * refresh job
 */
function _intern_job_refresh(&$node) {
  $sub_status = $node->field_job_sub_status[LANGUAGE_NONE][0]["value"];
  if ($sub_status == JOB_SUB_STATUS_PUBLISHED) {
    $node->changed = REQUEST_TIME;
    $deadline = $node->field_deadline[LANGUAGE_NONE][0]["value"];
    if ($node->changed >= $deadline - DATE_ONE_MONTH) {
      $node->field_deadline[LANGUAGE_NONE][0]["value"] = $node->changed + DATE_ONE_MONTH;
    }
  }
}

/**
 * @param $node
 * stop job
 */
function _intern_job_stop(&$node) {
  $sub_status = $node->field_job_sub_status[LANGUAGE_NONE][0]["value"];
  if ($sub_status == JOB_SUB_STATUS_PUBLISHED) {
    $node->status = NODE_NOT_PUBLISHED;
    $node->field_job_sub_status[LANGUAGE_NONE][0]["value"] = JOB_SUB_STATUS_STOPPED;
  }
}

/**
 * @param $node
 * republish job
 */
function _intern_job_republish(&$node) {
  $sub_status = $node->field_job_sub_status[LANGUAGE_NONE][0]["value"];
  if ($sub_status == JOB_SUB_STATUS_STOPPED || $sub_status == JOB_SUB_STATUS_EXPIRED) {
    $node->status = NODE_PUBLISHED;
    $node->field_job_sub_status[LANGUAGE_NONE][0]["value"] = JOB_SUB_STATUS_PUBLISHED;
    _intern_job_refresh($node);
  }
}

/**
 * @param $node
 * approve job
 */
function _intern_job_approve(&$node) {
  $node->status = NODE_PUBLISHED;
  $node->field_job_sub_status[LANGUAGE_NONE][0]["value"] = JOB_SUB_STATUS_PUBLISHED;
  $node->field_content_approval[LANGUAGE_NONE][0]["value"] = 0;
}

/**
 * @param $node
 * expire job
 */
function _intern_job_expire(&$node) {
  $node->status = NODE_NOT_PUBLISHED;
  $node->field_job_sub_status[LANGUAGE_NONE][0]["value"] = JOB_SUB_STATUS_EXPIRED;
}

function intern_job_form_node_form_alter(&$form, $form_state) {
  $type = $form['#node']->type;
  Global $user;

  if ($type == 'job' && intern_user_is_company_user()) {

    $form['og_group_ref']['und'][0]['target_id']['#type'] = 'hidden';

    hide($form["actions"]["delete"]);
    hide($form["field_job_sub_status"]);
    if (empty($form['field_email']['und'][0]['value']['#default_value'])) {
      $form['field_email']['und'][0]['value']['#default_value'] = $user->mail;
    }
    $form["actions"]["submit"]["#value"] = t('提交发布');
    $form["actions"]["draft"] = array(
      '#type' => 'submit',
      '#value' => t('保存草稿'),
      '#validate' => array('node_form_validate', 'intern_job_node_form_ant_submit'),
      '#submit' => array('node_form_submit', 'intern_job_node_form_post_submit'),
    );

    $form['#validate'][] = 'intern_job_node_form_ant_submit';
    $form['#submit'][] = 'intern_job_node_form_post_submit';
  }
}

function intern_job_node_form_ant_submit($form, &$form_state) {
  $values = $form_state['values'];
  $op = isset($values['op']) ? $values['op'] : '';

  $field_deadline = $form_state['values']['field_deadline'][LANGUAGE_NONE][0]["value"];
  if (isset($field_deadline) && !empty($field_deadline)) {
    if ($field_deadline <= time()) {
      form_set_error("field_deadline", "截止日期必须大于当前日期。");
    }
  }


  if ($op == t('保存草稿')) {
    $form_state['values']["field_job_sub_status"][LANGUAGE_NONE][0]['value'] = JOB_SUB_STATUS_DRAFT;
    $form_state['values']['status'] = NODE_NOT_PUBLISHED;
  }
  else {
    if ($op == t('提交发布')) {
      $form_state['values']["field_job_sub_status"][LANGUAGE_NONE][0]['value'] = JOB_SUB_STATUS_REQUIRE_APPROVAL;
    }
  }
}

function intern_job_node_form_post_submit($form, &$form_state) {
  $nid = $form_state['nid'];
  $values = $form_state['values'];
  $op = isset($values['op']) ? $values['op'] : '';

  $form_state['redirect'] = 'node/' . $nid . '/edit';
}

/**
 * Implements hook_action_info().
 */
function intern_job_action_info() {
  return array(
    'intern_job_stop_action' => array(
      'type' => 'node',
      'label' => t('暂停职位发布'),
      'configurable' => FALSE,
      'behavior' => array('changes_property'),
      'triggers' => array('node_presave'),
    ),
    'intern_job_refresh_action' => array(
      'type' => 'node',
      'label' => t('刷新职位'),
      'configurable' => FALSE,
      'behavior' => array('changes_property'),
      'triggers' => array('node_presave'),
    ),
    'intern_job_republish_action' => array(
      'type' => 'node',
      'label' => t('再发布职位'),
      'configurable' => FALSE,
      'behavior' => array('changes_property'),
      'triggers' => array('node_presave'),
    ),
    'intern_job_approve_action' => array(
      'type' => 'node',
      'label' => t('审核职位'),
      'configurable' => FALSE,
      'behavior' => array('changes_property'),
      'triggers' => array('node_presave'),
    ),

  );
}

/**
 * Sets the status of a node to 1 (published).
 *
 * @ingroup actions
 */
function intern_job_stop_action($node, $context = array()) {
  _intern_job_stop($node);
}

function intern_job_refresh_action($node, $context = array()) {
  _intern_job_refresh($node);
}

function intern_job_republish_action($node, $context = array()) {
  _intern_job_republish($node);
}

function intern_job_approve_action($node, $context = array()) {
  _intern_job_approve($node);
}

/**
 * Implements hook_cron().
 *
 * Expire jobs.
 */
function intern_job_cron() {
  $nids = db_query('SELECT fd.entity_id FROM {field_data_field_deadline} fd INNER JOIN {node} n ON fd.entity_id = n.nid  WHERE n.status=1 AND fd.field_deadline_value <= :request_time AND fd.bundle = :entity_type', array(
    ':request_time' => REQUEST_TIME,
    ':entity_type' => 'job'
  ))->fetchCol();
  if (!empty($nids)) {
    $jobs = node_load_multiple($nids);
    foreach ($jobs as $job) {
      _intern_job_expire($job);
      node_save($job);
    }
  }
  $nids = db_query('SELECT ca.entity_id FROM {field_data_field_content_approval} ca INNER JOIN {node} n ON ca.entity_id = n.nid  WHERE n.status=0 AND ca.field_content_approval_value = :need_approval AND ca.bundle = :entity_type', array(
    ':need_approval' => 1,
    ':entity_type' => 'job'
  ))->fetchCol();
  if (!empty($nids)) {
    $jobs = node_load_multiple($nids);
    foreach ($jobs as $job) {
      _intern_job_approve($job);
      node_save($job);
    }
  }
}

function intern_job_flags($jobId) {

  global $user;
  $_GET['destination'] = "node/" . $jobId;

  $output = '';
  if (!user_is_anonymous() && !intern_user_is_company_user()) {
    $output .= flag_create_link('collect', $jobId);
    //企业用户不能访问
    if (in_array(4, array_keys($user->roles))) {
    }
    else {
      if ($_SESSION['user_resume_finish_percent'] > 0) {
        $output .= flag_create_link('apply', $jobId);
      }
      else {
        $output .= '<span class="flag-wrapper flag-apply flag-apply-44312">
      <a href="javascript:alert(\'您还没有填写简历，请先完善简历。\')" title="" class="ctools-use-modal ctools-modal-ctools-ajax-register-style flag flag-action flag-link-normal" rel="nofollow">申请职位</a>
    </span>';
      }
    }

    $output .= '<span class="resume">';
    $path = 'node/add/resume';
    if (!empty($_SESSION['user_resume_id'])) {
      $path = 'node/' . $_SESSION['user_resume_id'] . '/edit';
    }
    $output .= l('填写简历', $path);
    $output .= '</span>';
  }

  return $output;
}

function intern_job_mail($key, &$message, $params) {
  switch ($key) {
    case 'job_apply':
//      $login_url = url("user/userregister/check/" . $params['uid'] . "/" . md5($params['pass'] . $params['mail'] . $params['login']), array('absolute' => TRUE));

      //	$account = $params['account'];
      //$context = $params['context'];
      $variables = array(
        '[site:name]' => variable_get('site_name', 'Drupal'),
        '[user:name]' => $params['user_name'],
        '[user:resume]' => $params['resume'],
        '[job:title]' => $params['job_title'],
        '[company:title]' => $params['company_title'],
        '[apply:date]' => $params['apply_date'],
      );
      $subject = '(54intern.com)申请贵公司[job:title] - [user:name]';
      $subject = strtr($subject, $variables);

      $body = '应聘职位：[job:title]<br>应聘公司：[company:title]<br>投递时间：[apply:date]<p>[user:resume]';
      $body = strtr($body, $variables);

      $message['subject'] = $subject;
      $message['body'][] = $body;
      drupal_set_message($body);
      break;

  }
}
