<?php

function intern_review_add_form($form, &$form_state) {
  $form = array();
  global $user;

  $node = (object) array(
    'uid' => $user->uid,
    'name' => (isset($user->name) ? $user->name : ''),
    'type' => 'review',
    'language' => LANGUAGE_NONE
  );
  field_attach_form('node', $node, $form, $form_state);
  $gid = arg(3);
  if (empty($gid)) {
    $gid = 0;
  }
  $form['og_group_ref']['und'][0]['target_id']['#type'] = 'hidden';
  $form['og_group_ref']['und'][0]['target_id']['#value'] = 'OG Company (' . $gid . ')';

  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('提交'),
  );

//  hide($form["field_company_evaluation"]);
//  hide($form["field_overall_value"]);
//  hide($form["field_treatment_value"]);
//  hide($form["field_training_value"]);
//  hide($form["field_regularize_value"]);

  $form['#validate'][] = 'intern_review_add_review_form_validate_handler';
  $form['#submit'][] = 'intern_review_add_review_form_submit_handler';
//  watchdog_array("Intern Company","Add Form Passed in",$form);

  $form["actions"]["submit"]["#value"] = t('提交点评');

  return $form;

}

function intern_review_add_review_form_validate_handler(&$form, &$form_state) {
  $pseudo_entity = (object) $form_state['values'];
  $pseudo_entity->type = 'review';
  field_attach_form_validate('node', $pseudo_entity, $form, $form_state);

  if (user_is_anonymous()) {
    form_set_error("对不起，匿名用户无法提交点评，赶快注册吧！");
  }
}


/**
 * Submit handler that builds and saves all profiles in the form.
 *
 */
function intern_review_add_review_form_submit_handler(&$form, &$form_state) {
  global $user;
  $pseudo_entity = (object) $form_state['values'];
  $pseudo_entity->type = 'review';
  $pseudo_entity->uid = $user->uid;
  $pseudo_entity->language = 'zh-hans';

  field_attach_submit('node', $pseudo_entity, $form, $form_state);
  node_save($pseudo_entity);
}

function intern_review_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'review_node_form') {
    honeypot_add_form_protection($form, $form_state, array('honeypot', 'time_restriction'));
    $form['title']['#required'] = false;
    $form["actions"]["submit"]["#value"] = t('提交点评');
  }
}

function intern_review_info_flags($reviewId) {
  global $user;
  $_GET['destination'] = "node/" . $reviewId;

  $output = '';
  if (!user_is_anonymous() ) {
    if(!intern_user_is_company_user()){
    $output .= flag_create_link('collect', $reviewId);
    $output .= flag_create_link('zan', $reviewId);}
    $output .= flag_create_link('report', $reviewId);
  }

  return $output;
}
